//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalGovi.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalGovi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///		O1.&quot;BD&quot; AS &quot;BaseDeDatos&quot;, O1.&quot;EMPRESA&quot; AS &quot;Empresa&quot;, O1.&quot;Cuenta&quot;, O1.&quot;NombreCuenta&quot;,
        ///		CAST(O1.&quot;INGRESO&quot; AS DECIMAL) AS &quot;Ingreso&quot;, CAST(O1.&quot;EGRESO&quot; AS DECIMAL) AS &quot;Egreso&quot;, CAST(O1.&quot;SALDO DIARIO&quot; AS DECIMAL) AS &quot;SaldoDiario&quot;, 
        ///		CAST(O1.&quot;SALDO INICIAL&quot; AS DECIMAL) AS &quot;SaldoInicial&quot;, CAST(CAST(&apos;{0}&apos; AS DATE) AS VARCHAR) AS &quot;Fecha&quot;
        ///		FROM
        ///	(
        ///		--&lt;INICIO SAN NICOLAS&gt;
        ///			SELECT 
        ///			&apos;SBOSANNICOLAS&apos; AS &quot;BD&quot;,&apos;GOVI SAN NICOLAS S DE RL DE CV&apos; AS &quot;EMPRESA&quot;, SN1.&quot;Cuenta&quot; ,SN1.&quot;NombreCuenta&quot;,
        ///			CAST( [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string SD_DIA {
            get {
                return ResourceManager.GetString("SD_DIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///&quot;Sociedad&quot;, 
        ///&quot;VATRegNum&quot;, 
        ///&quot;BankCtlKey&quot;, 
        ///&quot;MandateID&quot;, 
        ///&quot;Account&quot;, 
        ///&quot;DflAccount&quot;, 
        ///&quot;DocTotal&quot;, 
        ///&quot;DocNum&quot;, 
        ///IFNULL(&quot;JrnlMemo&quot;, &apos;&apos;) AS &quot;JrnlMemo&quot;, 
        ///&quot;County&quot;, &quot;LicTradNum&quot;, 
        ///&quot;IVA&quot;, 
        ///IFNULL(LEFT(&quot;E_Mail&quot;,39), &apos;&apos;) AS &quot;E_Mail&quot;, 
        ///&quot;DocDate&quot;, 
        ///&quot;CardName&quot;, 
        ///&quot;DocEntry&quot;,
        ///&quot;BPLName&quot;, 
        ///&quot;GLAccount&quot;
        ///FROM &quot;_SYS_BIC&quot;.&quot;ProductivaGOVI/DispersionUaU&quot; AS &quot;OVPM&quot; {0}.
        /// </summary>
        public static string SQL_TRANSFERENCIAS {
            get {
                return ResourceManager.GetString("SQL_TRANSFERENCIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///         &quot;Sociedad&quot;,
        ///         &quot;VATRegNum&quot;,
        ///         &quot;BankCtlKey&quot;, -- FORPAG
        ///         &quot;MandateID&quot;, -- CVESER
        ///         &quot;Account&quot;, -- CTAABO
        ///         &quot;DflAccount&quot;, -- IMPORTE
        ///         &quot;DocTotal&quot;,
        ///         &quot;DocNum&quot;,
        ///         &quot;JrnlMemo&quot;,
        ///         &quot;County&quot;,
        ///         &quot;LicTradNum&quot;,
        ///         &quot;IVA&quot;,
        ///         &quot;E_Mail&quot;, -- CORREO ELECTRÓNICO
        ///         &quot;DocDate&quot;,
        ///         &quot;CardName&quot;,
        ///         &quot;DocNum2&quot;,
        ///         &quot;DocEntry&quot;,
        ///         &quot;BPLName&quot;,
        ///         &quot;GLAccount&quot;,
        ///         &quot;REF01&quot;,
        ///         &quot; [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string SQL_TRANSFERENCIAS_SERVICIOS {
            get {
                return ResourceManager.GetString("SQL_TRANSFERENCIAS_SERVICIOS", resourceCulture);
            }
        }
    }
}
